-- WideWorldImporters_StockItems_SemanticSearch.sql

--========================================
-- 1. Prerequisites 
--========================================

-- SQL Server 2025
SELECT 
    @@VERSION AS VersionSQLServer;

USE [WideWorldImporters];
GO

-- Query the Warehouse.StockItems table
SELECT *
FROM Warehouse.StockItems;

SELECT TOP (10)
    StockItemID,
    StockItemName,
    SupplierID,
    ColorID,
    Brand,
    [Size],
    UnitPrice,
    MarketingComments,
    SearchDetails
FROM Warehouse.StockItems;

-- AI model that supports API calls: Ollama
-- Ollama model that generates embeddings: nomic-embed-text 
-- Proxy for Ollama: Caddy

--========================================
-- 2 Configuration
--========================================

-- Enable SQL Server 2025 preview features 
  
ALTER DATABASE SCOPED CONFIGURATION 
SET PREVIEW_FEATURES = ON;
GO

SELECT 
    name,
    value,
    value_for_secondary
FROM sys.database_scoped_configurations
WHERE name = 'PREVIEW_FEATURES';
GO

SELECT 
    name,
    compatibility_level
FROM sys.databases
WHERE name = 'WideWorldImporters';
GO

ALTER DATABASE WideWorldImporters 
SET COMPATIBILITY_LEVEL = 170;
GO


-- Enable API calls

USE master;
GO
sp_configure 'external rest endpoint enabled', 1;
GO
RECONFIGURE WITH OVERRIDE;
GO

--========================================
-- 3. Create credential
--========================================
USE [WideWorldImporters];
GO

-- Master Key
IF NOT EXISTS (
    SELECT *
    FROM sys.symmetric_keys
    WHERE [name] = '##MS_DatabaseMasterKey##'
)
BEGIN
    CREATE MASTER KEY
    ENCRYPTION BY PASSWORD = N'Use_A_Strong_Password_Here_123!';
    -- this password must be changed in a real environment.
END
GO

-- Drop the credential if it already exists
IF EXISTS (
    SELECT *
    FROM sys.database_scoped_credentials
    WHERE name = 'https://localhost:8443' -- Credential name (Caddy/Ollama endpoint)
)
BEGIN
    DROP DATABASE SCOPED CREDENTIAL [https://localhost:8443];
END
GO

-- Create the credential for Caddy/Ollama
CREATE DATABASE SCOPED CREDENTIAL [https://localhost:8443] 
WITH IDENTITY = 'HTTPEndpointHeaders',
SECRET = '{}'; -- Local Ollama normally does NOT require an API key.
GO

--=================================================================
-- 4.  Generate embeddings 
--=================================================================

-- Create the table for embeddings
USE [WideWorldImporters];
GO

DROP TABLE IF EXISTS dbo.ProductSemantic;
GO

CREATE TABLE dbo.ProductSemantic
(
    ProductSemanticID INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_ProductSemantic
        PRIMARY KEY CLUSTERED,

    StockItemID INT NOT NULL,             -- Unique identifier of the original product

    StockItemName NVARCHAR(100) NOT NULL, -- Product name, useful for displaying results

    SemanticText NVARCHAR(MAX) NOT NULL,  -- Final text used to generate the embedding

    Embedding vector(768) NULL            -- Vector generated by nomic-embed-text
);
GO

INSERT INTO dbo.ProductSemantic
(
    StockItemID,
    StockItemName,
    SemanticText,
    Embedding
)
SELECT
    StockItemID,
    StockItemName,
    SearchDetails AS SemanticText, -- Computed text used for searches
    NULL AS Embedding
FROM Warehouse.StockItems;
GO

-- Create an index on the alternate key
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductSemantic_StockItemID
ON dbo.ProductSemantic (StockItemID);
GO

-- Query the embeddings table
SELECT *
FROM dbo.ProductSemantic;

SELECT TOP (10)
    ProductSemanticID,
    StockItemID,
    StockItemName,
    SemanticText,
    Embedding
FROM dbo.ProductSemantic;

-- Create the external model
USE [WideWorldImporters];
GO

IF EXISTS (
    SELECT 1
    FROM sys.external_models
    WHERE name = N'OllamaNomicEmbed'
)
BEGIN
    DROP EXTERNAL MODEL OllamaNomicEmbed;
END;
GO

CREATE EXTERNAL MODEL OllamaNomicEmbed
WITH 
( 
    LOCATION = 'https://localhost:8443/api/embed', 
    API_FORMAT = 'Ollama', 
    MODEL_TYPE = EMBEDDINGS, 
    MODEL = 'nomic-embed-text' 
);
GO

-- Check that the object has been stored
SELECT *
FROM sys.external_models;

-- Generate embeddings with AI_GENERATE_EMBEDDINGS
USE [WideWorldImporters];
GO

UPDATE dbo.ProductSemantic
SET Embedding =
    CAST(
        AI_GENERATE_EMBEDDINGS(
            SemanticText
            USE MODEL OllamaNomicEmbed
        )
        AS vector(768)
    )
WHERE Embedding IS NULL;
GO

-- Query the embeddings table 
SELECT *
FROM dbo.ProductSemantic;

SELECT TOP (10)
    ProductSemanticID,
    StockItemID,
    StockItemName,
    SemanticText,
    Embedding
FROM dbo.ProductSemantic;

-- Create the vector index
IF EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'IX_ProductSemantic_Embedding'
      AND object_id = OBJECT_ID(N'dbo.ProductSemantic')
)
BEGIN
    DROP INDEX IX_ProductSemantic_Embedding
    ON dbo.ProductSemantic;
END;
GO

-- Check that all embeddings have been generated before creating the index
SELECT
    COUNT(*) AS TotalProducts,
    SUM(CASE WHEN Embedding IS NOT NULL THEN 1 ELSE 0 END) AS ProductsWithEmbedding,
    SUM(CASE WHEN Embedding IS NULL THEN 1 ELSE 0 END) AS ProductsWithoutEmbedding
FROM dbo.ProductSemantic;
GO


CREATE VECTOR INDEX IX_ProductSemantic_Embedding
ON dbo.ProductSemantic (Embedding)
WITH
(
    METRIC = 'cosine',
    TYPE = 'DiskANN'
);
GO

--=====================================================
-- 5. Create stored procedures using the 
--    vector index for semantic product search
--=====================================================
/*
    Procedure: dbo.find_relevant_product_names_vector_index

    - Simple output 
    
    - Returns only the names of the semantically related products.
*/
USE [WideWorldImporters];
GO

CREATE OR ALTER PROCEDURE dbo.find_relevant_product_names_vector_index
    @prompt NVARCHAR(MAX),                 -- User search text
    @top INT = 10,                         -- Maximum number of returned products
    @min_similarity DECIMAL(19,16) = 0.3   -- Minimum accepted similarity
AS
BEGIN
    SET NOCOUNT ON;

    -- Basic validation of the search text
    IF @prompt IS NULL OR LTRIM(RTRIM(@prompt)) = N''
    BEGIN
        RAISERROR(N'Debe indicar un texto de búsqueda en @prompt.', 16, 1);
        RETURN;
    END;

    -- Basic validation of the number of results
    IF @top IS NULL OR @top <= 0
    BEGIN
        SET @top = 10;
    END;

    DECLARE @queryEmbedding vector(768);

    /*
        -- Generates the embedding for the user's query
        -- SQL Server calls the external model OllamaNomicEmbed,
           which in turn uses Ollama with nomic-embed-text.
    */
    SET @queryEmbedding =
        CAST(
            AI_GENERATE_EMBEDDINGS(
                @prompt
                USE MODEL OllamaNomicEmbed
            )
            AS vector(768)
        );
    /*
        -- Use VECTOR_SEARCH to compare the query vector with stored 
           product embeddings and return the closest product names
    */
    SELECT
        ps.StockItemName AS ProductName
    FROM VECTOR_SEARCH
    (
        TABLE = dbo.ProductSemantic AS ps,
        COLUMN = Embedding,
        SIMILAR_TO = @queryEmbedding,
        METRIC = 'cosine',
        TOP_N = @top
    ) AS vs
    WHERE CAST(1 - vs.distance AS DECIMAL(19,16)) >= @min_similarity
    ORDER BY vs.distance ASC;
END;
GO

--======================================================
-- DEMO SP: dbo.find_relevant_product_names_vector_index
--======================================================

EXEC dbo.find_relevant_product_names_vector_index
    @prompt = N'usb gadget',
    @top = 10,
    @min_similarity = 0.3;
GO

/*
    Notice:
        -Some results, although they do not contain “USB”,
         still belong to the same semantic context of 
         technology-related items.

        - Semantic search may return some less relevant results.
          This can happen when the embedding model considers them
          close to part of the user query.
 */

/*
    Semantic search allows queries in different languages.
    However, results are usually better when the query language
    is close to the language used in the stored product text.

    For example: To search for "I’m looking for a funny 
                                computer-related gift"
*/
-- In Spanish
EXEC dbo.find_relevant_product_names_vector_index
    @prompt = N'busco un regalo gracioso relacionado con informática',
    @top = 10,
    @min_similarity = 0.3;
GO

-- In Setswana
EXEC dbo.find_relevant_product_names_vector_index
    @prompt = N'Ke batla mpho e e tshegisang e e amanang le dikhomphutha',
    @top = 10,
    @min_similarity = 0.3;
GO

/*
    Procedure: dbo.find_relevant_products_vector_index

    - Technical view.

    - Shows SemanticText, distance and similarity.
*/
USE [WideWorldImporters];
GO

CREATE OR ALTER PROCEDURE dbo.find_relevant_products_vector_index
    @prompt NVARCHAR(MAX),                 -- User search text
    @top INT = 10,                         -- Maximum number of returned products
    @min_similarity DECIMAL(19,16) = 0.3   -- Minimum accepted similarity
AS
BEGIN
    SET NOCOUNT ON;

    -- Basic validation of the search text
    IF @prompt IS NULL OR LTRIM(RTRIM(@prompt)) = N''
    BEGIN
        RAISERROR(N'Debe indicar un texto de búsqueda en @prompt.', 16, 1);
        RETURN;
    END;

    -- Basic validation of the number of results
    IF @top IS NULL OR @top <= 0
    BEGIN
        SET @top = 10;
    END;

    DECLARE @queryEmbedding vector(768);
        
    SET @queryEmbedding =
        CAST(
            AI_GENERATE_EMBEDDINGS(
                @prompt
                USE MODEL OllamaNomicEmbed
            )
            AS vector(768)
        );

    SELECT
        ps.ProductSemanticID,
        ps.StockItemID,
        ps.StockItemName,
        ps.SemanticText,
        vs.distance, 
            -- low distance: more similar product
        CAST(1 - vs.distance AS DECIMAL(19,16)) AS similarity
            -- high similarity: more similar product
    FROM VECTOR_SEARCH
    (
        TABLE = dbo.ProductSemantic AS ps,
        COLUMN = Embedding,
        SIMILAR_TO = @queryEmbedding,
        METRIC = 'cosine',
        TOP_N = @top
    ) AS vs
    WHERE CAST(1 - vs.distance AS DECIMAL(19,16)) >= @min_similarity
    ORDER BY vs.distance ASC;
END;
GO

--======================================================
-- DEMO SP: dbo.find_relevant_products_vector_index
--======================================================

EXEC dbo.find_relevant_products_vector_index
    @prompt = N'usb gadget',
    @top = 10,
    @min_similarity = 0.3;
GO

EXEC dbo.find_relevant_products_vector_index
    @prompt = N'busco un regalo gracioso relacionado con informática',
    @top = 10,
    @min_similarity = 0.3;
GO

/*
    Procedure: dbo.find_relevant_stock_items_vector_index

    - Real-world case.

    - Combines semantic search with business data.

*/
USE [WideWorldImporters];
GO

CREATE OR ALTER PROCEDURE dbo.find_relevant_stock_items_vector_index
    @prompt NVARCHAR(MAX),
    @top INT = 10,
    @min_similarity DECIMAL(19,16) = 0.3
AS
BEGIN
    SET NOCOUNT ON;

    IF @prompt IS NULL OR LTRIM(RTRIM(@prompt)) = N''
    BEGIN
        RAISERROR(N'Debe indicar un texto de búsqueda en @prompt.', 16, 1);
        RETURN;
    END;

    IF @top IS NULL OR @top <= 0
    BEGIN
        SET @top = 10;
    END;

    DECLARE @queryEmbedding vector(768);

    SET @queryEmbedding =
        CAST(
            AI_GENERATE_EMBEDDINGS(
                @prompt
                USE MODEL OllamaNomicEmbed
            )
            AS vector(768)
        );

    SELECT
        si.StockItemName AS ProductName,
        ISNULL(si.Brand, N'Not specified') AS Brand,
        ISNULL(c.ColorName, N'Not specified') AS Color,
        ISNULL(si.[Size], N'Not specified') AS ProductSize,
        si.TypicalWeightPerUnit AS TypicalWeight,
        si.RecommendedRetailPrice AS RecommendedPrice,
        ISNULL(si.MarketingComments, N'Not specified') AS MarketingComments
    FROM VECTOR_SEARCH
    (
        TABLE = dbo.ProductSemantic AS ps,
        COLUMN = Embedding,
        SIMILAR_TO = @queryEmbedding,
        METRIC = 'cosine',
        TOP_N = @top
    ) AS vs
    INNER JOIN Warehouse.StockItems AS si
        ON si.StockItemID = ps.StockItemID 
    LEFT JOIN Warehouse.Colors AS c
        ON si.ColorID = c.ColorID
    WHERE CAST(1 - vs.distance AS DECIMAL(19,16)) >= @min_similarity
    ORDER BY vs.distance ASC;
END;
GO

--======================================================
-- DEMO SP: dbo.find_relevant_stock_items_vector_index
--======================================================

EXEC dbo.find_relevant_stock_items_vector_index
    @prompt = N'usb gadget',
    @top = 10,
    @min_similarity = 0.3;
GO

EXEC dbo.find_relevant_stock_items_vector_index
    @prompt = N'busco un regalo gracioso relacionado con informática',
    @top = 10,
    @min_similarity = 0.3;
GO

--======================================================
-- NOTE: To run searches once everything is working correctly
--======================================================
/* 
1. Check that Ollama is running.

   In PowerShell:
   curl http://localhost:11434/api/tags

   It should return information about the installed models,
   including "nomic-embed-text".

   If it is not running, open the Ollama application or run:
   ollama serve

2. Start Caddy.

   In another PowerShell window:
   cd C:\caddy
   .\caddy.exe run --config Caddyfile

   Check the HTTPS endpoint:
   curl https://localhost:8443/api/tags
*/